### ISSUE TITLE
 Downloaded JSONL Files Are 0KB

### ISSUE THREAD

**Issue by GreatGBL** [potamides/arxiv-latex-extract#1] opened 2024-06-01 21:52 UTC
Hello,

I am encountering an issue where the JSONL files generated by the script are 0KB in size. Here are the details of the problem:

I cloned the repository and followed the instructions to run the script. However, the output JSONL files are empty, with a size of 0KB. I have ensured that the script runs without errors and that the data should be present, but the output files do not contain any data.

!git clone https://github.com/potamides/arxiv-latex-extract.git
%cd arxiv-latex-extract
!pip install -r requirements.txt
!python main.py

Cloning into 'arxiv-latex-extract'...
remote: Enumerating objects: 43, done.
remote: Counting objects: 100% (43/43), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 43 (delta 22), reused 32 (delta 14), pack-reused 0
Receiving objects: 100% (43/43), 18.87 KiB | 1.89 MiB/s, done.
Resolving deltas: 100% (22/22), done.
/content/arxiv-latex-extract/arxiv-latex-extract/arxiv-latex-extract
Requirement already satisfied: internetarchive==3.5.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (3.5.0)
Requirement already satisfied: tqdm==4.65.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (4.65.0)
Requirement already satisfied: docopt<0.7.0,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from internetarchive==3.5.0->-r requirements.txt (line 1)) (0.6.2)
Requirement already satisfied: jsonpatch>=0.4 in /usr/local/lib/python3.10/dist-packages (from internetarchive==3.5.0->-r requirements.txt (line 1)) (1.33)
Requirement already satisfied: requests<3.0.0,>=2.25.0 in /usr/local/lib/python3.10/dist-packages (from internetarchive==3.5.0->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: schema>=0.4.0 in /usr/local/lib/python3.10/dist-packages (from internetarchive==3.5.0->-r requirements.txt (line 1)) (0.7.7)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from internetarchive==3.5.0->-r requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.10/dist-packages (from jsonpatch>=0.4->internetarchive==3.5.0->-r requirements.txt (line 1)) (2.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.25.0->internetarchive==3.5.0->-r requirements.txt (line 1)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.25.0->internetarchive==3.5.0->-r requirements.txt (line 1)) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests<3.0.0,>=2.25.0->internetarchive==3.5.0->-r requirements.txt (line 1)) (2024.2.2)
Parallel processing on 2 workers.
  0% 0/2900 [00:00<?, ?it/s]ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16365.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16346.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16327.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16276.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16359.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16290.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16347.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16352.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16291.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16315.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16351.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16367.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16370.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16340.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16369.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16386.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16362.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16406.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16391.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16389.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16415.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16338.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16292.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16319.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16385.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16388.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16360.gz
ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16381

**Comment by potamides** [comment] 2024-06-03 10:13
I have tried to reproduce your issue, but on my end everything worked fine. The `ERROR:root:FileNotFoundError: /tmp/tmpl5co4v_n/tmp79rrwrwq/2010/2010.16360.gz` errors suggest that the code cannot find the archives downloaded from arxiv, which is why the `jsonl` files are empty. Did you change the paths in any way?

**Comment by GreatGBL** [comment] 2024-06-03 14:17
Thank you for your response. I just tested it on Colab, but I still have the same problem; it's still showing a FileNotFoundError.

!git clone https://github.com/potamides/arxiv-latex-extract.git
import os
os.chdir('/content/arxiv-latex-extract')
print("Current working directory:", os.getcwd())
!pip install -r requirements.txt
!python main.py

**Comment by potamides** [comment] 2024-06-04 10:17
You did not install `latexpand`, try this:

```diff
  !git clone https://github.com/potamides/arxiv-latex-extract.git
  import os
  os.chdir('/content/arxiv-latex-extract')
  print("Current working directory:", os.getcwd())
  !pip install -r requirements.txt
+ !apt install texlive-extra-utils
  !python main.py
```
The error messages could definitely be improved.

**Comment by GreatGBL** [comment] 2024-06-04 15:49
> You did not install `latexpand`, try this:
> 
> ```diff
>   !git clone https://github.com/potamides/arxiv-latex-extract.git
>   import os
>   os.chdir('/content/arxiv-latex-extract')
>   print("Current working directory:", os.getcwd())
>   !pip install -r requirements.txt
> + !apt install texlive-extra-utils
>   !python main.py
> ```
> 
> The error messages could definitely be improved.

TY it works and sorry for my careless

**Comment by potamides** [comment] 2024-06-05 08:48
No worries, the error messages are definitely misleading :) Since your problem seems to be solved, I will close this issue. Thank you for your interest in this project!

**Closed as completed by potamides** 2024-06-05 08:48 UTC
